### ISSUE TITLE
Blinking

### ISSUE THREAD

**Issue by skunkwerk** [YueWuHKUST/AniFaceGAN#3]
Thanks for this great work.  None of the videos seem to support blinking, even though https://github.com/sicxu/Deep3DFaceRecon_pytorch seems to support closed eyes.  Any ideas how to fix this?

thanks

**Comment by kathrinawu** [comment]
This is because, in the FFHQ dataset, there are only a few pictures of people with their eyes closed or eyes blinking. In [Deep3DFaceRecon_pytorch](https://github.com/sicxu/Deep3DFaceRecon_pytorch), they can not reconstruct the eye-blinking scenes due to data distribution. Thus, our work does not support eye blinking as our work is conducted using [Deep3DFaceRecon_pytorch](https://github.com/sicxu/Deep3DFaceRecon_pytorch).

For this limitation,
there are two possible ways to fix the problem.
1. Use data containing eye-blinking scene to fine-tune [Deep3DFaceRecon_pytorch](https://github.com/sicxu/Deep3DFaceRecon_pytorch), then fine-tune our method.
2. Use stronger prior from 3dmm to force the eyes to be blinking.
